#!/usr/bin/env bash
# displays Best School 10 times and Hi in the 9 itteration

count=1

while [ $count -le 10 ]
do
	if [ $count != 9 ]; then
		echo "Best School"
	fi
	if [ $count = 9 ]; then
		echo "Hi"
	fi
	((count++))
done
